### ISSUE TITLE
Unreadable text when using block cursor

### ISSUE THREAD

**Issue by kepbod** [arcticicestudio/nord-iterm2#2]
Same issues as described in [nord-vim issue #9](https://github.com/arcticicestudio/nord-vim/issues/9).

**Comment by arcticicestudio** [comment]
Fixed by using `nord1` for the "Cursor Text" option.

<p align="center"><strong>Before</strong><br><img src="https://cloud.githubusercontent.com/assets/7836623/21782939/83fc004c-d6b5-11e6-84ac-a05fdee61fa5.png"/><br><strong>After</strong><br><img src="https://cloud.githubusercontent.com/assets/7836623/21782954/942b03aa-d6b5-11e6-9f52-af2a2d737b1a.png"/></p>

**Comment by arcticicestudio** [comment]
🚢 Shipped in release version [0.2.0](https://github.com/arcticicestudio/nord-iterm2/releases/tag/v0.2.0)
You can delete the old version from within the *Presets* drop-down list via *Remove Color Scheme* and then import the new version.
